import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <head>
        <Script 
          src="https://expulsiondatabaseinnocent.com/d4/1e/ec/d41eec995d21d55bcc35a752a969fee0.js" 
          strategy="afterInteractive"
          // Ini memastikan iklan dimuat setelah halaman utama siap
        />
      </head>
      <body>
        {children}
        
        {/* PASANG IKLAN DI SINI */}
        <Script 
          src="https://expulsiondatabaseinnocent.com/d4/1e/ec/d41eec995d21d55bcc35a752a969fee0.js" 
          strategy="afterInteractive"
          // Ini memastikan iklan dimuat setelah halaman utama siap
        />
      </body>
    </html>
  );
}